language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install coverage pyhamcrest lxml js2py flake8

before_script:
    - flake8 --exclude=__init__.py --ignore=E501 ptp/

script:
    - make check

notifications:
    email: false
